---
- name: systemd restart blackbox_exporter
  systemd:
    name: blackbox_exporter
    state: restarted
    daemon_reload: yes

- name: initd restart blackbox_exporter
  service:
    name: blackbox_exporter
    state: restarted
