---
# monit/meta/main.yml

galaxy_info:
    author: Roman Belyakovsky, Roman Tishchenko
    description: Install and configure Prometheus
    license: MIT

    min_ansible_version: 2.0

    platforms:
        - name: Ubuntu
          versions:
              - precise
              - trusty
        - name: Debian
          versions:
              - jessie
              - wheezy
        - name: CentOS
          versions:
              - 6
              - 7
    galaxy_tags:
        - system
        - monitoring
        - prometheus

dependencies: []
