---
- name: systemd restart pushgateway
  systemd:
    name: pushgateway
    state: restarted
    daemon_reload: yes

- name: initd restart pushgateway
  service:
    name: pushgateway
    state: restarted
