---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: test -e /usr/bin/python || (apt update && apt install -y python-minimal)
      changed_when: false
    - name: gather facts
      setup:
  tasks:
    - name: install libselinux-python binary for ansible to work
      yum: name=libselinux-python state=present
      when: ansible_pkg_mgr == 'yum' and not ansible_selinux

- hosts: all
  roles:
    - role: pushgateway